### ISSUE TITLE
检测到更新后未通知至qq

### ISSUE THREAD

**Issue by Glyty** [Audirntttttttt/TwitterToQQPy#1]

**Comment by Glyty** [comment]
![G0 G {1TO6FGC(VX_5R713E](https://user-images.githubusercontent.com/33739017/69521778-bc7e5e80-0f9a-11ea-9500-5b4d0dbaae4c.png)

**Comment by Audirntttttttt** [comment]
可能是你一次要发的太多了，每次执行时间超过了定时器模块的限定值后，没有走到发送消息的语句就被中断了

**Comment by Glyty** [comment]
刚才我只留了小狐狸，还是出现了这个情况
这个会因为没发到qq然后反复发送么

**Comment by Audirntttttttt** [comment]
不会反复发送的
暂时不清楚你的情况具体是啥，你试试在 mian.py 37 行 加一个参数 max_instances=10 应该是可以解决你的报错，但是可能会不稳定，或者被反爬封ip

**Comment by Glyty** [comment]
![image](https://user-images.githubusercontent.com/33739017/69555372-0c324980-0fde-11ea-9c64-11640363fa47.png)
参数的话我是这样设置的，但在我的qq上接受不到关于推文的内容（不知道是没发送到还是发送过去了没显示

**Comment by Audirntttttttt** [comment]
api_root = 'http://10.0.0.31:5700'

**Comment by Glyty** [comment]
改了下，酷q那边还是接收不到消息。

**Comment by Glyty** [comment]
想问下；检测不全是因为什么呢（现在能发过来但只有几条。
